Repository elastic/ebpf, pull requests merged in 2022-01, with the labels that each got.

#53 Add support for deleting a single item from map
  non-GPL/HostIsolationMapsUtil/UpdateMaps.c
  non-GPL/HostIsolationMapsUtil/UpdateMaps.h
Labels: please review

#50 docs: add build instructions for RPM distros
  README.md
Labels: please review, Team: Endpoint Cloud

#60 EventProbe: implement EBPF_EVENT_FILE_CREATE
  GPL/EventProbe/BPFEventsTests.cpp
  GPL/EventProbe/EbpfEventProto.h
  GPL/EventProbe/EventProbe.bpf.c
  GPL/EventProbe/Helpers.h
  non-GPL/EventsTrace/EventsTrace.c
  non-GPL/LibEbpfEvents/LibEbpfEvents.c
Labels: Team: Endpoint Cloud
